CONJOINT PLAN= 'C:\Users\Phani\Documents\Cars.sav'
    /DATA='C:\Users\Phani\Documents\cars_prefs2.sav'
    /SEQUENCE=PREF1 TO PREF53
    /SUBJECT=CUSTOMER_ID
    /FACTORS=BRAND EXTERIOR_DESIGN (DISCRETE) 
     PRICE (LINEAR LESS)
     TORQUE (LINEAR MORE) ADVANCED_DRIVER_ASSISTANCE_SYSTEM (LINEAR MORE)
     AIRBAGS(LINEAR MORE) ANTILOCK_BRAKING_SYSTEM(LINEAR MORE)
    /PLOT=ALL  
    /PRINT=SUMMARYONLY.
